    services:
  - type: web
    name: RePosture-backend
    env: docker
    repo: https://github.com/developer-amarjeetBaraik/RePosture
    dockerfilePath: Backend/Dockerfile
    buildFilter:
      paths:
        - Backend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
