services:
  - type: web
    name: RePosture-backend
    env: node
    rootDir: Backend
    buildCommand: |
      npm install
      pip install -r Backend/requirements.txt
    startCommand: node app.js